feat: AL-6 Add linting to the pre-commit step

diff --git a/.git-hooks/pre-commit b/.git-hooks/pre-commit
--- a/.git-hooks/pre-commit
+++ b/.git-hooks/pre-commit
@@ -1,3 +1,20 @@
 #!/bin/sh
 
+# This makes sure that if any simple command (straightforward commands not under any expression) fails,
+# The whole script immediately fails
+set -e
+
+# Step 0: Remember all the files that are not staged for this commit, comes in later
+UNSTAGED_FILES=$(git diff --name-only)
+
+# Step 1: Run the linting of affected files. Just fix automatically if possible
+yarn nx affected:lint --uncommitted --fix
+
+# Step 1.cleanup: We need to stage the files that the lint fixed. For that, we do a diff with the original unstaged
+# and add those files
+UNSTAGED_FILES_AFTER_LINT=$(git diff --name-only)
+FILES_TO_BE_ADDED=$(echo "$UNSTAGED_FILES\n$UNSTAGED_FILES_AFTER_LINT" | sort | uniq -u)
+echo $FILES_TO_BE_ADDED | xargs git add
+
+# Step last: Format all staged files and re-stage them
 yarn pretty-quick --staged
